// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIbxwwOfLXMmpLg3Oi6Sw6LYRjLjeVMnY',
    appId: '1:658068574958:web:5476671882876beaff19ff',
    messagingSenderId: '658068574958',
    projectId: 'shoppe-app-76689',
    authDomain: 'shoppe-app-76689.firebaseapp.com',
    storageBucket: 'shoppe-app-76689.firebasestorage.app',
    measurementId: 'G-SBXK7W66RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRm741pA2v64pgVlrxq5615bEOfTc-E9Y',
    appId: '1:658068574958:android:1998ea6877393488ff19ff',
    messagingSenderId: '658068574958',
    projectId: 'shoppe-app-76689',
    storageBucket: 'shoppe-app-76689.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg4ygNoMQn-Iwju8uYRVuR_WeYw59-8To',
    appId: '1:658068574958:ios:ce3b37add6e9adf9ff19ff',
    messagingSenderId: '658068574958',
    projectId: 'shoppe-app-76689',
    storageBucket: 'shoppe-app-76689.firebasestorage.app',
    iosBundleId: 'com.example.shoppe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIbxwwOfLXMmpLg3Oi6Sw6LYRjLjeVMnY',
    appId: '1:658068574958:web:05e737371157c0feff19ff',
    messagingSenderId: '658068574958',
    projectId: 'shoppe-app-76689',
    authDomain: 'shoppe-app-76689.firebaseapp.com',
    storageBucket: 'shoppe-app-76689.firebasestorage.app',
    measurementId: 'G-C6Z2YHSYMV',
  );
}
